import React from 'react';
import { BarChart3, TrendingUp, PieChart, Layers, ShieldCheck, Target, ArrowUpRight } from 'lucide-react';

export default function AnalyticsView({ trades }) {
  // Compute Strategy Breakdown
  const strategies = {};
  trades.forEach((t) => {
    const strat = t.strategy || 'Uncategorized';
    if (!strategies[strat]) {
      strategies[strat] = { total: 0, wins: 0, losses: 0, pnl: 0 };
    }
    strategies[strat].total += 1;
    if (t.status === 'WIN') strategies[strat].wins += 1;
    if (t.status === 'LOSS') strategies[strat].losses += 1;
    strategies[strat].pnl += Number(t.pnl) || 0;
  });

  // Compute Symbol Breakdown
  const symbols = {};
  trades.forEach((t) => {
    const sym = t.symbol;
    if (!symbols[sym]) {
      symbols[sym] = { total: 0, wins: 0, pnl: 0 };
    }
    symbols[sym].total += 1;
    if (t.status === 'WIN') symbols[sym].wins += 1;
    symbols[sym].pnl += Number(t.pnl) || 0;
  });

  return (
    <div className="space-y-8 text-left animate-fade-in">
      {/* Top Header */}
      <div>
        <h2 className="text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
          Analytics & Statistics Center
          <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 font-semibold">
            Statistical Edge
          </span>
        </h2>
        <p className="text-xs text-foreground/60 mt-1">
          Deep-dive performance breakdowns to isolate what actually produces compounding profitability
        </p>
      </div>

      {/* Grid of Strategy & Symbol Breakdown */}
      <div className="grid lg:grid-cols-2 gap-6">
        {/* Strategy Performance Matrix */}
        <div className="glass-card p-6">
          <div className="flex items-center justify-between mb-4 border-b border-border pb-3">
            <div>
              <h3 className="text-base font-bold text-foreground">Strategy & Setup Win Rates</h3>
              <p className="text-xs text-foreground/60">Effectiveness of each model in live market</p>
            </div>
            <Layers className="w-5 h-5 text-brand-teal" />
          </div>

          <div className="space-y-4">
            {Object.entries(strategies).map(([name, data]) => {
              const wr = data.total > 0 ? ((data.wins / data.total) * 100).toFixed(0) : 0;
              return (
                <div key={name} className="p-3.5 rounded-2xl border border-border bg-background/50">
                  <div className="flex justify-between items-center text-xs font-semibold mb-2">
                    <span className="text-foreground">{name}</span>
                    <div className="flex items-center gap-3">
                      <span className="font-mono text-brand-teal">{wr}% Win Rate</span>
                      <span className={`font-mono font-bold ${data.pnl >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                        {data.pnl >= 0 ? `+$${data.pnl.toLocaleString()}` : `-$${Math.abs(data.pnl).toLocaleString()}`}
                      </span>
                    </div>
                  </div>
                  <div className="w-full bg-card rounded-full h-2 overflow-hidden border border-border">
                    <div
                      className="bg-gradient-brand h-full rounded-full transition-all duration-500"
                      style={{ width: `${wr}%` }}
                    ></div>
                  </div>
                  <div className="flex justify-between text-[10px] text-foreground/50 mt-1.5 font-mono">
                    <span>{data.total} Trades Executed</span>
                    <span>{data.wins} Wins / {data.losses} Losses</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Symbol Profitability Heatmap */}
        <div className="glass-card p-6">
          <div className="flex items-center justify-between mb-4 border-b border-border pb-3">
            <div>
              <h3 className="text-base font-bold text-foreground">Symbol Profitability Matrix</h3>
              <p className="text-xs text-foreground/60">Net PnL generated by instrument</p>
            </div>
            <Target className="w-5 h-5 text-brand-blue" />
          </div>

          <div className="space-y-3">
            {Object.entries(symbols).map(([sym, data]) => {
              const wr = data.total > 0 ? ((data.wins / data.total) * 100).toFixed(0) : 0;
              return (
                <div key={sym} className="flex items-center justify-between p-3 rounded-xl border border-border bg-background/50 text-xs">
                  <div className="flex items-center gap-2.5">
                    <span className="font-bold text-sm text-foreground">{sym}</span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-card border border-border text-foreground/70">
                      {data.total} Trades
                    </span>
                  </div>

                  <div className="flex items-center gap-4">
                    <span className="font-mono text-foreground/70">{wr}% WR</span>
                    <span className={`font-mono font-bold text-sm ${data.pnl >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {data.pnl >= 0 ? `+$${data.pnl.toLocaleString()}` : `-$${Math.abs(data.pnl).toLocaleString()}`}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Additional Stats: R:R & Sessions */}
      <div className="grid sm:grid-cols-3 gap-6">
        <div className="glass-card p-6">
          <span className="text-xs uppercase font-semibold text-foreground/60 block mb-1">Average Risk : Reward</span>
          <div className="text-3xl font-bold text-foreground mt-1">1 : 2.85</div>
          <p className="text-xs text-brand-teal mt-2">Allows high profitability even at 40% win rate</p>
        </div>

        <div className="glass-card p-6">
          <span className="text-xs uppercase font-semibold text-foreground/60 block mb-1">Trade Expectancy</span>
          <div className="text-3xl font-bold text-emerald-400 mt-1">+$1,450.00</div>
          <p className="text-xs text-foreground/60 mt-2">Expected mathematical return per execution</p>
        </div>

        <div className="glass-card p-6">
          <span className="text-xs uppercase font-semibold text-foreground/60 block mb-1">Max Drawdown</span>
          <div className="text-3xl font-bold text-foreground mt-1">-1.85%</div>
          <p className="text-xs text-emerald-400 mt-2">Safely within Prop Firm 10% limit</p>
        </div>
      </div>
    </div>
  );
}
